name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Install Firefox and Geckodriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
        wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        tar -xvzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        rm geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz

    - name: Test Firefox and Geckodriver
      run: |
        geckodriver --version
        firefox --version

    - name: Run tests
      run: pytest tests/ --maxfail=5 -v
